# Generated by Django 3.2.15 on 2026-06-09 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_version_1_3_part_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PourInProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='When the pour started.')),
                ('ticks', models.IntegerField(default=0, help_text='Current flow meter ticks.')),
                ('volume_ml', models.FloatField(default=0, help_text='Current volume in milliliters.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp.')),
                ('keg_tap', models.ForeignKey(help_text='The tap being poured from.', on_delete=django.db.models.deletion.CASCADE, to='core.kegtap')),
                ('meter', models.ForeignKey(help_text='The flow meter recording the pour.', on_delete=django.db.models.deletion.CASCADE, to='core.flowmeter')),
                ('user', models.ForeignKey(blank=True, help_text='User pouring the drink.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pour In Progress',
                'verbose_name_plural': 'Pours In Progress',
            },
        ),
    ]
