# Generated by Django 3.2.15 on 2026-07-11 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pourinprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegbotsite',
            name='keg_indicator_critical_percent',
            field=models.PositiveIntegerField(default=5, help_text='Escalate to the "ALMOST EMPTY" indicator when the keg is at most this percent full (or when the critical pints threshold is crossed, whichever comes first).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='kegbotsite',
            name='keg_indicator_critical_pints',
            field=models.PositiveIntegerField(default=4, help_text='Escalate to the "ALMOST EMPTY" indicator when at most this many pints remain (or when the critical percent threshold is crossed, whichever comes first).'),
        ),
        migrations.AddField(
            model_name='kegbotsite',
            name='keg_indicator_low_percent',
            field=models.PositiveIntegerField(default=15, help_text='Show the "LOW KEG" indicator when the keg is at most this percent full (or when the low pints threshold is crossed, whichever comes first).', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='kegbotsite',
            name='keg_indicator_low_pints',
            field=models.PositiveIntegerField(default=10, help_text='Show the "LOW KEG" indicator when at most this many pints remain (or when the low percent threshold is crossed, whichever comes first).'),
        ),
    ]
