# Generated by Django 3.2.15 on 2026-07-26

from django.db import migrations, models

DEFAULT_TAP_PLACEHOLDER_SENTENCES = "\n".join(
    [
        "The taps are dry… but not for long.",
        "Currently pouring: absolutely nothing.",
        "A moment of silence for the kegs we've finished.",
        "Good beer comes to those who wait.",
        "404: Beer not found. Restocking soon.",
        "Somewhere out there, a keg has our name on it.",
        "The taps are napping. Please do not disturb.",
        "Intermission — the next act is still fermenting.",
        "All kegs have gone to a better place. (Our stomachs.)",
        "Fresh kegs loading…",
        "This space reserved for your next favorite beer.",
        "Empty taps are just full taps waiting to happen.",
        "We drank it all. We regret nothing.",
        "Stay tuned — hops springs eternal.",
        "The kegerator is between gigs.",
        "New kegs are on the way. Probably.",
    ]
)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kegbotsite_keg_indicator_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegbotsite',
            name='tap_placeholder_sentences',
            field=models.TextField(blank=True, default=DEFAULT_TAP_PLACEHOLDER_SENTENCES, help_text='Shown on the fullscreen display when no kegs are tapped; one sentence per line, cycled in random order. Leave blank to show nothing.'),
        ),
    ]
