# Generated by Django 3.2.15 on 2026-07-26

from django.db import migrations, models

OLD_SENTENCES = [
    "The taps are dry… but not for long.",
    "Currently pouring: absolutely nothing.",
    "A moment of silence for the kegs we've finished.",
    "Good beer comes to those who wait.",
    "404: Beer not found. Restocking soon.",
    "Somewhere out there, a keg has our name on it.",
    "The taps are napping. Please do not disturb.",
    "Intermission — the next act is still fermenting.",
    "All kegs have gone to a better place. (Our stomachs.)",
    "Fresh kegs loading…",
    "This space reserved for your next favorite beer.",
    "Empty taps are just full taps waiting to happen.",
    "We drank it all. We regret nothing.",
    "Stay tuned — hops springs eternal.",
    "The kegerator is between gigs.",
    "New kegs are on the way. Probably.",
]

NEW_SENTENCES = OLD_SENTENCES + [
    "Barley there — new kegs arriving soon.",
    "The beer is in another castle.",
    "Shh… the kegs are in witness protection.",
    "Technically, air is on tap.",
    "Now serving: anticipation.",
    "The next keg is still in beer school.",
    "Zero beers on tap. This is not a drill.",
    "Please hold — your beer is important to us.",
    "Out of beer. In our defense, it was delicious.",
    "The taps demand a sacrifice: one fresh keg.",
    "Keg status: gone, but not forgotten.",
    "This bar is currently running on vibes.",
    "Breaking news: local taps report feeling thirsty too.",
    "Insert keg to continue.",
    "The foam has settled. For now.",
    "Today's special: a tall glass of patience.",
    "Rumor has it a keg is on its way.",
    "Draft picks coming soon.",
    "Achievement unlocked: drank the whole keg.",
    "Hops and dreams.",
]

OLD_DEFAULT = "\n".join(OLD_SENTENCES)
NEW_DEFAULT = "\n".join(NEW_SENTENCES)


def add_new_sentences(apps, schema_editor):
    """Upgrades sites still using the original default sentence list."""
    KegbotSite = apps.get_model("core", "KegbotSite")
    KegbotSite.objects.filter(tap_placeholder_sentences=OLD_DEFAULT).update(
        tap_placeholder_sentences=NEW_DEFAULT
    )


def remove_new_sentences(apps, schema_editor):
    KegbotSite = apps.get_model("core", "KegbotSite")
    KegbotSite.objects.filter(tap_placeholder_sentences=NEW_DEFAULT).update(
        tap_placeholder_sentences=OLD_DEFAULT
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kegbotsite_tap_placeholder_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegbotsite',
            name='tap_placeholder_sentences',
            field=models.TextField(blank=True, default=NEW_DEFAULT, help_text='Shown on the fullscreen display when no kegs are tapped; one sentence per line, cycled in random order. Leave blank to show nothing.'),
        ),
        migrations.RunPython(add_new_sentences, remove_new_sentences),
    ]
