# Generated by Django 3.2.15 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_more_tap_placeholder_sentences"),
    ]

    operations = [
        migrations.AddField(
            model_name="kegbotsite",
            name="keg_indicator_empty_pints",
            field=models.PositiveIntegerField(
                default=3,
                help_text='Escalate to the "EMPTY" indicator when at most this many pints remain.',
            ),
        ),
    ]
